## Numpy


## Addition


In [ ]:
import numpy as np

x = [1,2,3,4,5]
y = [6,7,8,9,10]

array1 = np.array(x)
array2 = np.array(y)

result = array1 + array2

print(result)


[ 7  9 11 13 15]


## Substraction

In [4]:
import numpy as np

x = [6,7,8,9,10]
y = [1,2,3,4,5]

array1 = np.array(x)
array2 = np.array(y)

result = array1 - array2

print(result)

[5 5 5 5 5]


## Multiplication

In [5]:
import numpy as np

lst = [1,2,3,4]

array = np.array(lst)

result = array * 2

print(result)


[2 4 6 8]


## Division

In [6]:
import numpy as np

x= [15,26,37,48,53]
y = [2,3,4,5,6]

array1 = np.array(x)
array2 = np.array(y)

result = array1 / array2

print(result)

[7.5        8.66666667 9.25       9.6        8.83333333]


## Scalar arthmetic

mathmetical operations on single value

In [9]:
import numpy as np

#lst = [1,2,3,4,5]

array = np.array([1,2,3,4,5])

print(array + 1)
print(array - 1)
print(array / 4)
print(array * 2)
print(array ** 3)


[2 3 4 5 6]
[0 1 2 3 4]
[0.25 0.5  0.75 1.   1.25]
[ 2  4  6  8 10]
[  1   8  27  64 125]


## Vector arthmetic



In [10]:
import numpy as np

array1 = np.array([1,2,3,4,5,6])
array2 = np.array([1.0,2.3,5.1,8.6])

print(np.sqrt(array1))
print(np.round(array2))
print(np.floor(array2))
print(np.pi)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[1. 2. 5. 9.]
[1. 2. 5. 8.]
3.141592653589793


## 2Dimensional array

In [12]:
import numpy as np

A = np.array([[1,2],
             [3,4]])

B = np.array([[5,6],
             [7,8]])

print(A.shape)
print(A*B)

(2, 2)
[[ 5 12]
 [21 32]]


## Indexing


In [ ]:
import numpy as np

lst = [[[1,2,3],[4,5,6],[7,8,9]]]
lst = np.array(lst)


#print(lst)
print(lst[0][2][1])

print(lst[0][2])
print(lst.ndim)

print(lst.shape)

8
[7 8 9]
3
(1, 3, 3)


## Nested lst

## Multiplication

In [ ]:
nested_lst = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

result = np.array(nested_lst)
result =result * 5
print(result)



[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


## Addition

In [24]:
nested_lst = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

print(nested_lst[0] + nested_lst[1])
new_result = np.array(nested_lst)
print(new_result [0] + new_result[1])

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [ ]:
for i in range(100,-1,-5):
    print(i)


100
95
90
85
80
75
70
65
60
55
50
45
40
35
30
25
20
15
10
5
0


In [37]:
for i in range(0,105,+5):
    print(i)

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100


## slicing

In [39]:
import numpy as np

lst = [1,2,3,4,5,6,7,8,9]
result = np.array(lst)

print("1. result [1:8] -> Elements from index 1 to 7 :",result[1:8])

print("2. result[1:] -> Elements from index 1 to end :",result[1:])

print("3. result[:1] -> Elements from start to index 0 :", result[::-1])


1. result [1:8] -> Elements from index 1 to 7 : [2 3 4 5 6 7 8]
2. result[1:] -> Elements from index 1 to end : [2 3 4 5 6 7 8 9]
3. result[:1] -> Elements from start to index 0 : [9 8 7 6 5 4 3 2 1]


## Negative slicing

In [46]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9,10])

print("4. array[-3:-1] -> From 3rd last to 2nd last element :" , array[-3:-1])

print("5. array[::3] -> Every 3rd element : " , array [::3])



4. array[-3:-1] -> From 3rd last to 2nd last element : [8 9]
5. array[::3] -> Every 3rd element :  [ 1  4  7 10]


## Slicing 2D array

In [5]:
import numpy as np

nested_lst = [
    [1,2,3,4,5,6,7,8,9,0],
    [0,9,8,7,6,5,4,3,2,1]
]

new_array = np.array(nested_lst)

print(new_array [0 , 0:4])
print(new_array [0:2 , 5])
print(new_array [0:2 , 1:4])


[1 2 3 4]
[6 5]
[[2 3 4]
 [9 8 7]]
