## Numpy


## Addition


In [ ]:
import numpy as np

x = [1,2,3,4,5]
y = [6,7,8,9,10]

array1 = np.array(x)
array2 = np.array(y)

result = array1 + array2

print(result)


[ 7  9 11 13 15]


## Substraction

In [4]:
import numpy as np

x = [6,7,8,9,10]
y = [1,2,3,4,5]

array1 = np.array(x)
array2 = np.array(y)

result = array1 - array2

print(result)

[5 5 5 5 5]


## Multiplication

In [5]:
import numpy as np

lst = [1,2,3,4]

array = np.array(lst)

result = array * 2

print(result)


[2 4 6 8]


## Division

In [6]:
import numpy as np

x= [15,26,37,48,53]
y = [2,3,4,5,6]

array1 = np.array(x)
array2 = np.array(y)

result = array1 / array2

print(result)

[7.5        8.66666667 9.25       9.6        8.83333333]


## Scalar arthmetic

mathmetical operations on single value

In [9]:
import numpy as np

#lst = [1,2,3,4,5]

array = np.array([1,2,3,4,5])

print(array + 1)
print(array - 1)
print(array / 4)
print(array * 2)
print(array ** 3)


[2 3 4 5 6]
[0 1 2 3 4]
[0.25 0.5  0.75 1.   1.25]
[ 2  4  6  8 10]
[  1   8  27  64 125]


## Vector arthmetic



In [10]:
import numpy as np

array1 = np.array([1,2,3,4,5,6])
array2 = np.array([1.0,2.3,5.1,8.6])

print(np.sqrt(array1))
print(np.round(array2))
print(np.floor(array2))
print(np.pi)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[1. 2. 5. 9.]
[1. 2. 5. 8.]
3.141592653589793


## 2Dimensional array

In [12]:
import numpy as np

A = np.array([[1,2],
             [3,4]])

B = np.array([[5,6],
             [7,8]])

print(A.shape)
print(A*B)

(2, 2)
[[ 5 12]
 [21 32]]


## Indexing


In [ ]:
import numpy as np

lst = [[[1,2,3],[4,5,6],[7,8,9]]]
lst = np.array(lst)


#print(lst)
print(lst[0][2][1])

print(lst[0][2])
print(lst.ndim)

print(lst.shape)

8
[7 8 9]
3
(1, 3, 3)


## Nested lst

## Multiplication

In [ ]:
nested_lst = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

result = np.array(nested_lst)
result =result * 5
print(result)



[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


## Addition

In [24]:
nested_lst = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

print(nested_lst[0] + nested_lst[1])
new_result = np.array(nested_lst)
print(new_result [0] + new_result[1])

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [ ]:
for i in range(100,-1,-5):
    print(i)


100
95
90
85
80
75
70
65
60
55
50
45
40
35
30
25
20
15
10
5
0


In [37]:
for i in range(0,105,+5):
    print(i)

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100


## slicing

In [39]:
import numpy as np

lst = [1,2,3,4,5,6,7,8,9]
result = np.array(lst)

print("1. result [1:8] -> Elements from index 1 to 7 :",result[1:8])

print("2. result[1:] -> Elements from index 1 to end :",result[1:])

print("3. result[:1] -> Elements from start to index 0 :", result[::-1])


1. result [1:8] -> Elements from index 1 to 7 : [2 3 4 5 6 7 8]
2. result[1:] -> Elements from index 1 to end : [2 3 4 5 6 7 8 9]
3. result[:1] -> Elements from start to index 0 : [9 8 7 6 5 4 3 2 1]


## Negative slicing

In [46]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9,10])

print("4. array[-3:-1] -> From 3rd last to 2nd last element :" , array[-3:-1])

print("5. array[::3] -> Every 3rd element : " , array [::3])



4. array[-3:-1] -> From 3rd last to 2nd last element : [8 9]
5. array[::3] -> Every 3rd element :  [ 1  4  7 10]


## Slicing 2D array

In [5]:
import numpy as np

nested_lst = [
    [1,2,3,4,5,6,7,8,9,0],
    [0,9,8,7,6,5,4,3,2,1]
]

new_array = np.array(nested_lst)

print(new_array [0 , 0:4])
print(new_array [0:2 , 5])
print(new_array [0:2 , 1:4])


[1 2 3 4]
[6 5]
[[2 3 4]
 [9 8 7]]


## 1D Array Slicing

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(arr[2:6]) 

print(arr[3:])

print(arr[:4])

[30 40 50 60]
[40 50 60 70 80]
[10 20 30 40]


## Negative Slicing

In [2]:
arr = np.array([5, 10, 15, 20, 25, 30, 35])

print(arr[-3:])

print(arr[-3:-2])

[25 30 35]
[25]


## Step Slicing

In [3]:
arr = np.array([2, 4, 6, 8, 10, 12, 14, 16])

print(arr[::2])

print(arr[1::3])

[ 2  6 10 14]
[ 4 10 16]


## matrix multiplication

Matrix multiplication is how the network learns and transforms data.

Matrix multiplication is used in Al to combine many input features with weights at once to produce outputs - this is how neural networks make predictions.

This is how a neural network layer works:

inputs x weights → outputs


In [6]:

import numpy as np

A = np.array([[1,2],

(3,4)])

B = np.array([[5,6], [7,8]])

print(np.matmul(A,B))

print(A)

print(A.dot(B))


[[19 22]
 [43 50]]
[[1 2]
 [3 4]]
[[19 22]
 [43 50]]


no of columns in first numpy array = no of rows in second numpy array

example:-

add product inherit

ald Python exercis id getter and poly id Python exampl ld decorator tial commit tial commit


In [ ]:
import numpy as np

X = np.array([[170, 65, 20]])
W = np.array([
    [0.2, 0.4],
    [0.5, 0.1],
    [0.3, 0.7]
])

output = X @ W
print(output)

m, n, p = 1, 3, 2
array1 = m * n
array2 = n * p
print(f"array1 = (m * n) -> ({m}*{n})")
print(f"array2 = (n * p) -> ({n}*{p})")


## Concatenation

In [4]:
import numpy as np

A = np.array([[1,2,3]])
B = np.array([[4,5,6]])
C = np.concatenate((A,B),axis=0) #row - wise
print(C)
C = np.concatenate((A,B),axis=1) #column - wise
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


 ## Aggregate Functions in NumPy
 
Aggregate functions are used to summarize data.
They usually take an array as input and return a single value (or summary).
Examples: sum, mean, max, min, argmin, argmax, etc.

In [3]:
import numpy as np

array = np.array([
    [11,12,13,14,15],
    [26,27,28,29,30]
])

print("Sum of all elements : ", np.sum(array))
print("Mean (average) :", np.mean(array))

print("Maximum value :", np.max(array))
print("Minimum value :", np.min(array))

print("Index of minimum value :",np.argmin(array))
print("Index of maximum value :",np.argmax(array))


Sum of all elements :  205
Mean (average) : 20.5
Maximum value : 30
Minimum value : 11
Index of minimum value : 0
Index of maximum value : 9


## Sum across column and rows

In [4]:
import numpy as np

array = np.array ([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

#Sum across Columns (axis=0)
print ("Columns-wise sum : ",np.sum(array,axis=0))

#Sum across Rows (axis=1)
print("Row-wise sum : ",np.sum(array,axis=1))

Columns-wise sum :  [ 7  9 11 13 15]
Row-wise sum :  [15 40]


## Random

In [ ]:
import numpy as np

arrat = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

print("Product of all elements :",np.prod(array))

print(array.size)

rand_array = np.random.randint(1,101,size=5)
print(rand_array)


Product of all elements : 3628800
10
[13  2 42 20 52]


## Reshape

In [3]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9])

# print(array.shape)

reshaped = array.reshape(3,3)

print("reshape():\n",reshaped)


reshape():
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Flatten / Ravel / Transpose

In [6]:
import numpy as np

#flatten

array2D = np.array([[1,2,3],[4,5,6]])
flat = array2D.flatten()
print("flatten():",flat)

#ravel

array2D = np.array([[10,20,30],[40,50,60]])
ravelled = array2D.ravel()
print("ravel():",ravelled)

#transpose

array2D = np.array([[1,2,3],[4,5,6]])
transposed = array2D.transpose()
print("transpose():",transposed)



flatten(): [1 2 3 4 5 6]
ravel(): [10 20 30 40 50 60]
transpose(): [[1 4]
 [2 5]
 [3 6]]


## Vstack / Hstack 

In [11]:
import numpy as np

a = np.array([1,2,3])

b = np.array([4, 5, 6])
vertical = np.vstack((a,b))
horizontal = np.hstack((a,b))

print("vstack():\n",vertical)
print("hstack():",horizontal)


vstack():
 [[1 2 3]
 [4 5 6]]
hstack(): [1 2 3 4 5 6]


## Split

In [8]:
import numpy as np

array = np.array([10,20,30,40,50,60])
parts = np.split(array,3)
print("split():",parts)

split(): [array([10, 20]), array([30, 40]), array([50, 60])]


## Unique

In [12]:
import numpy as np

array = np.array([1,2,3,4,6,3,54,4,2,2,5,4,1,34,56,56])
unique_values = np.unique(array)
print("unique():",unique_values)

unique(): [ 1  2  3  4  5  6 34 54 56]


## numpy filtring()

In [16]:
import numpy as np

array = np.array([
    [50,60,70,80,90],
    [85,96,48,56,58]

])

marks = array[array>40]
print ("All marks > 40:",marks)

new_marks = array[(array > 40) & (array < 90)]
print("Mark between 40 and 90 :",new_marks)

updated_marks = array[(array <90)]
print(updated_marks)



All marks > 40: [50 60 70 80 90 85 96 48 56 58]
Mark between 40 and 90 : [50 60 70 80 85 48 56 58]
[50 60 70 80 85 48 56 58]
